### ISSUE TITLE
Publish migrated watcher

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/watcher#103]

**Comment by maks** [comment]
I'm guessing this is in regards to migrating this package to Null Safety.
@natebosch are you looking for contributions to migrate this package to NS or is that already on someones to do list?

**Comment by natebosch** [comment]
The package is migrated, what is pending is publishing. I'll close this issue after it's published.

**Comment by maks** [comment]
oops sorry about that @natebosch! I looked only in the list of branches, not seeing it had already been merged to master.

**Comment by natebosch** [comment]
This is published.
