### ISSUE TITLE
Does it work synchronously?

### ISSUE THREAD

**Issue by scheglov** [dart-lang/watcher#114]
Is it supposed to work for the following scenario?

1. Enter a synchronous function.
2. Start watching a directory.
3. Do some synchronous operation that takes a few seconds.
4. While this operation is performed, the used changes a file in the watched directory.
5. Done doing the synchronous operation.
6. Cancel the watcher.

Will we get events about the changed file?
I'm asking because it does not work for me, and I wonder if this is a know limitation, or I'm holding it wrong.
Context: https://github.com/dart-lang/linter/issues/2694#issuecomment-861774481

**Comment by jakemac53** [comment]
Is this just a byproduct of the fact that the watcher package uses streams which asynchronously deliver events? If you were to delay the cancelling of the watcher for a bit, do you get the events then?

**Comment by scheglov** [comment]
Sounds plausible. I get events sometimes, if I delay `cancel` for `5 seconds`. When I don't get them, it might be either because there is something in `package:watcher`, or (most probably) because I start watching still not soon enough.

So, I cannot prove that it for sure has an issue.

**Comment by scheglov** [comment]
I experimented some more, opened https://github.com/dart-lang/watcher/issues/115 instead.
