### ISSUE TITLE
FileSystemException: Failed to watch path, path = '/Users/xxx/yyy/zzz' (OS Error: No such file or directory, errno = 2)

### ISSUE THREAD

**Issue by scheglov** [dart-lang/watcher#126]
We started to see many of these in crash logs from Dart analysis server in the last week or two. On Linux. Probably during `analysis.setAnalysisRoots` handling, but maybe it is reported from there, but caused by some IO that happened much later.

The search for the error message brings me here: https://github.com/dart-lang/sdk/blob/935ee25f3b72e7fe81047220cadae1f61c505da4/sdk/lib/_internal/vm/bin/file_patch.dart#L183

@DanTup @bwilkerson

**Comment by DanTup** [comment]
@scheglov is it specific to a single OS? Do you know if they're VS Code/LSP clients or not? Is there any pattern to the paths being reported (do they look like roots, or sub-folders nested within roots)?

The two recent changes I made are:

- watcher: https://github.com/dart-lang/watcher/commit/f76997ab0c857dc5537ac0975a9ada92b54ef949
- sdk: https://github.com/dart-lang/sdk/commit/650b9627b7a7c05d9d2a489a23b2eae98c9aef95

The watcher changes don't see like they should cause any _new_ errors, so I wonder if it's the SDK change. Do you know what date it started occurring? Does it match up with the SDK change? (or [update of watcher](https://github.com/dart-lang/sdk/commit/423055d5267c9a1e7b449e2f6da56715d0d42338))

**Comment by scheglov** [comment]
The first time I see it is `Tue, 18 Jan 2022 16:03:24 GMT` in version `2.17.422473333-edge+google3-v2`. So, it could be both.

It looks that there was an exception thrown from `_watchPath`, but I have not idea when and why this happens. I guess only VM people could know.

**Comment by DanTup** [comment]
I think this error is normal if we try to create a `DirectoryWatcher` for a directory that doesn't exist - although I can't see anything obvious in either of my changes that would've changed any behaviour in that area. I'm fairly sure one of the changes above must have caused this though, if not directly, perhaps as a result of us no longer dropping some events when the context rebuilds 🤔

Do you have any answers for the above? Which OSes, and do the folders look like things that would probably be roots themselves, or children of roots? Are they LSP clients or not? (the timing of setting roots might be different with LSP because they can be changed by open/closing files).

**Comment by scheglov** [comment]
I see it only happening with `analysis.setAnalysisRoots` request, so not LSP. But "the absence of evidence is not the evidence of absence".

Because all these crash logs are from Google users, it is all Linux.

These paths looks that there are roots themselves.

Another error message: `FileSystemException: FileSystemException: Failed to watch path, path = '/google/src/xxx' (OS Error: Transport endpoint is not connected, errno = 107)`.

Very often `Process update` is less than a second, like `781 ms`, sometimes between 1 and 2 seconds, sometimes slightly more, but always soon after start.

**Comment by scheglov** [comment]
I can reproduce this exception on Linux when running `DirectoryWatcher('...').events.listen(...)`: `FileSystemException: Failed to watch path, path = 'xxx' (OS Error: No such file or directory, errno = 2)`. On Mac it was slightly different: `FileSystemException: Directory listing failed, path = '/Users/scheglov/tmp/xxx' (OS Error: No such file or directory, errno = 2)`. So, it looks that  this is a missing error handling in DAS.

Not a `package:watcher` issue anyway. So, I'm closing it.

**Comment by DanTup** [comment]
@scheglov do you have a fix, or is it something I should look at? How did you reproduce it?

**Comment by scheglov** [comment]
I don't have a fix yet.

The server [should](https://github.com/dart-lang/sdk/blob/540c053ca845ca45eeeff7504f91b60d69528d87/pkg/analysis_server/tool/spec/spec_input.html#L812) handle the absence of an analysis root and ignore it. But when it becomes available, it should start analyzing it.
