### ISSUE TITLE
Updating of symlink files doesn't works

### ISSUE THREAD

**Issue by kelegorm** [dart-lang/watcher#2]
I'm not so cleare here, but. I have a 'web' folder with packages folder into. And I want to have a copy of this folder in special path. So, what's going on. I have a project:
```
myProject
|_ lib
   |_ main_app.html
   |_ main_app.dart
|_ packages /*...*/
|_ web
   |_ app.html
```
So If I make `pub upgrade` all files will be updated, all good. But then I change main_app.html component and save it, so, there is not update in 'web' folder. DirectoryWatcher can't catch it.

To resolve this I added special looking for 'lib' folder in my [script](https://gist.github.com/kelegorm/b08643f3a8f863e6243c).

**Comment by nex3** [comment]
Unfortunately, the underlying OS API (at least on OS X) simply doesn't support reporting events for files within symlinked directories. In theory we could detect when a subdirectory is a symlink and set up a sub-watcher for it, but that would add a huge amount of complexity that I doubt would be worth it.
