### ISSUE TITLE
add events for unavailable network filesystems?

### ISSUE THREAD

**Issue by skybrian** [dart-lang/watcher#23]
Some filesystems are network filesystems, and the network isn't always available. We have users who lose connectivity every night until they reauthenticate in the morning.

It seems like a filesystem-specific watcher should have a way to send an event that connection to the filesystem was lost, followed by another event when the connection resumes. Often the file or directory hasn't changed at all, just our connection to it. (Of course, on resume, some files may have changed.)

**Comment by nex3** [comment]
`dart:io` doesn't expose this information, and I'm not sure the underlying OS APIs do either. I'm going to mark this blocked until we have an API we can use to watch for connectivity.

**Comment by skybrian** [comment]
Actually, I'm not asking for the standard watchers to be modified to support these new events, and it doesn't matter if dart:io supports them.

Even though watchers don't officially support a plugin API for filesystem-specific plugins, that's what we're doing via a patch. We have our own subclasses of FileWatcher and DirectoryWatcher.

However, these subclasses don't have a way to change the public API, and the analysis server (or pub serve, I suppose) probably shouldn't import our subclasses directly.

So, maybe the question is how to support custom events. We need some API that exists but does nothing for the standard watchers, but that interested clients can use to get these events. Clients that don't care about them don't need to subscribe.

Strawman: suppose there were a ChangeType.CUSTOM, WatchEvent had an extra "custom" field of type dynamic, and the DirectoryWatcher factory took an extra map of custom options to pass to the specific instance of DirectoryWatcher?

That's fairly ugly, but what's a cleaner way to do it?

**Comment by nex3** [comment]
Do these events need to go through the standard watcher stream? Could you expose your own stream that emits your own event types?

**Comment by skybrian** [comment]
I think it could be a separate stream. Since they're all delivered via microtasks they should arrive in the right order.

Which Dart library do the event types live in? The custom watcher code and the clients who care will need to depend on it.

Let's say we have a separate network-fs-watcher package that defines the extra API. It has to be open source since the clients are open source. How do we plug that into watcher? (Or do we?)

**Comment by nex3** [comment]
I'd define something like:

```dart
// package:network_fs_watcher/network_fs_watcher.dart

class NetworkFSWatcher implements DirectoryWatcher {
  Stream<NetworkEvent> get networkEvents;

  // Implementation of DirectoryWatcher interface.
}
```

**Comment by skybrian** [comment]
Sounds good.
