### ISSUE TITLE
clarify lifecycle for Watcher.isReady

### ISSUE THREAD

**Issue by skybrian** [dart-lang/watcher#24]
A `Watcher` has an `isReady` property that returns true when it's ready. There is also a `ready` property that returns a `Future`.

Once `isReady` returns true, can it ever return false? Could this be used to indicate that a watcher is temporarily unavailable? If so, perhaps we could add a way to wait for a filesystem to go offline:

```
/// Completes when the watcher is no longer ready.
///
/// This can be used to find out when a watcher becomes unavailable.
/// (A watcher that's not ready doesn't send any events.)
/// If not ready, returns an already completed Future.
Future notReady;
```

Then we could use this API to solve the unavailable network filesystem problem as discussed in #23.

Or if that's not the intention, maybe the docs should explicitly say that once a watcher becomes ready, it remains ready.

**Comment by nex3** [comment]
I think this is pretty clear from the existing API. `ready` returns a future, which can only complete once, and `isReady` explicitly says that it's true if and only if `ready` is complete.

I still think the best solution to #23 is for your custom watcher to expose its own stream to surface its own filesystem events.

**Comment by skybrian** [comment]
Okay, thanks!

The reason I asked is that "returns a future" isn't quite as strict as "always returns the same Future". For example, Window.animationFrame is a getter that returns a Future, but it periodically changes to new one.
