### ISSUE TITLE
Master has not been in a publishable state for ~2 years

### ISSUE THREAD

**Issue by grouma** [dart-lang/watcher#41]
The last actual work on master was for symlinks: https://github.com/dart-lang/watcher/commit/dd6c0dc59b415c681089143f6ba0b2b13a350dbd

Since this feature has not been finished in such a long time, it should just be removed and we should merge in 0.9.7+x.

**Comment by nex3** [comment]
I don't want to delete the work on master; it fixes #18 on Linux, and this package *should* have that behavior on all operating systems. I haven't had the resources allocated to do that, but it's good work that shouldn't just be thrown away.

**Comment by grouma** [comment]
Are you comfortable with releasing master even if the feature isn't complete?

**Comment by nex3** [comment]
I think it's important to limit the behavioral differences between operating systems. On master, symlinks work *vastly* differently on Linux than they do on Mac OS or Windows.

**Comment by natebosch** [comment]
@kevmoo - can you do the branch rename dance? I don't think I'll have permission?

**Comment by kevmoo** [comment]
Uh....sure...

**Comment by kevmoo** [comment]
Done!

**Comment by kevmoo** [comment]
Careful when syncing this down. You're git client will be annoyed if you try to pull...
