### ISSUE TITLE
Cannot consume latest package:test

### ISSUE THREAD

**Issue by grouma** [dart-lang/watcher#42]
This package depends on the deprecated `pacakge:scheduled_test` which has a tight constraint on `package:test` of `>=0.12.20 <0.12.21`. Unfortunately this is blocking Google3 rolls of `package:test` and must be addressed. Ideally, the tests in this package should be rewritten to not depend on the deprecated package.

**Comment by nex3** [comment]
I believe @grouma is currently on this.

**Comment by natebosch** [comment]
I don't see a dep on scheduled_test in either branch.

**Comment by grouma** [comment]
I removed the dep in this PR and should have closed this bug then: https://github.com/dart-lang/watcher/commit/c81b6306987b922cf5f3121fce5525523b430f0d
