### ISSUE TITLE
Dart 2 runtime failures in tests

### ISSUE THREAD

**Issue by keertip** [dart-lang/watcher#53]
Running tests in Dart 2 mode,

00:01 +0 -1: does not notify for files that already exist when started [E]                                                                                                                             
  type '_BroadcastStream<dynamic>' is not a subtype of type 'Stream<FileSystemEvent>' where
    _BroadcastStream is from dart:async
    Stream is from dart:async
    FileSystemEvent is from dart:io
  
  dart:io                                                                               FileSystemEntity.watch
  package:watcher/src/directory_watcher/linux.dart 67:10                                new _LinuxDirectoryWatcher
  package:watcher/src/directory_watcher/linux.dart 31:36                                new LinuxDirectoryWatcher.<fn>
  package:watcher/src/resubscribable.dart 47:21                                         new ResubscribableWatcher.<fn>
  dart:async                                                                            _StreamImpl.listen
  package:async/src/stream_queue.dart 524:37                                            _StreamQueue._ensureListening
  package:async/src/stream_queue.dart 491:7                                             StreamQueue._addRequest
  package:async/src/stream_queue.dart 128:7                                             StreamQueue.hasNext
  ../..watcher/test/utils.dart 76:18                     startWatcher
  ===== asynchronous gap ===========================
  dart:async                                                                            new Future.microtask
  ../..watcher/test/utils.dart 60:26                     startWatcher
  ../.watcher/test/directory_watcher/shared.dart 16:11  sharedTests.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                                            new Future.microtask
  ../../dart/watcher/test/directory_watcher/shared.dart 11:69  sharedTests.<fn>

00:03 +0 -1: doesn't notify if the file isn't modified [E]                                                                                                                                             
  type '_BroadcastStream<dynamic>' is not a subtype of type 'Stream<FileSystemEvent>' where
    _BroadcastStream is from dart:async
    Stream is from dart:async
    FileSystemEvent is from dart:io
  
  dart:io                                                                          FileSystemEntity.watch
  package:watcher/src/file_watcher/native.dart 46:10                               _NativeFileWatcher._listen
  package:watcher/src/file_watcher/native.dart 36:5                                new _NativeFileWatcher
  package:watcher/src/file_watcher/native.dart 19:31                               new NativeFileWatcher.<fn>
  package:watcher/src/resubscribable.dart 47:21                                    new ResubscribableWatcher.<fn>
  dart:async                                                                       _StreamImpl.listen
  package:async/src/stream_queue.dart 524:37                                       _StreamQueue._ensureListening
  package:async/src/stream_queue.dart 491:7                                        StreamQueue._addRequest
  package:async/src/stream_queue.dart 128:7                                        StreamQueue.hasNext
  ../..//watcher/test/utils.dart 76:18                startWatcher

and more ...

**Comment by nex3** [comment]
Blocked on https://github.com/dart-lang/sdk/issues/33027

**Comment by keertip** [comment]
@nex3 , blocking issue has been fixed and dev build released.

**Comment by nex3** [comment]
I believe this was closed by #54.
