### ISSUE TITLE
How to listen screenshot folder?

### ISSUE THREAD

**Issue by jonataslaw** [dart-lang/watcher#74]
Applications such as Snap watch the device screenshots folder, and if there are any changes while it is open, it issues a warning. Is it possible to do this with this plugin?

**Comment by munificent** [comment]
Yes, it should be. This package can watch any directory.

**Comment by natebosch** [comment]
To accomplish this you'll need to know the filesystem path for the directory your are interested in watching. The flutter team will be best equipped to help you solve that.
