### ISSUE TITLE
Doesn't work on Android creating a directory.

### ISSUE THREAD

**Issue by sgehrman** [dart-lang/watcher#90]
I'm on Android. I watch a folder, I do a Directory.createSync, watcher doesn't fire. If I delete a different file, it fires fine, but I get like 7 events for that one operation.

**Comment by cachapa** [comment]
It seems that directory creation and deletion events are not being reported by this package in any platform.

At least on Linux those events are reported by the OS, but from looking at the source code they are only used to trigger a watch in the subdirectory:
https://github.com/dart-lang/watcher/blob/master/lib/src/directory_watcher/linux.dart#L89-L90

Change events are only emitted for files: 
https://github.com/dart-lang/watcher/blob/master/lib/src/directory_watcher/linux.dart#L200-L206

Hopefully I'm not misinterpreting that code, but it seems that the fix might be relatively simple at least on Linux. It might require adding a new change event type for directories though.

**Comment by filly82** [comment]
doesn't work on windows either :-(

**Comment by natebosch** [comment]
I'll close this in favor of a prior request for adding directory events. https://github.com/dart-lang/watcher/issues/1
